//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLIENT_CONSOLE.NS_WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="C_USER", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class C_USER : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        private int AgeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NS_WS.C_GESTION_USERSSoap")]
    public interface C_GESTION_USERSSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément P_User de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ajoute_User", ReplyAction="*")]
        CLIENT_CONSOLE.NS_WS.Ajoute_UserResponse Ajoute_User(CLIENT_CONSOLE.NS_WS.Ajoute_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ajoute_User", ReplyAction="*")]
        System.Threading.Tasks.Task<CLIENT_CONSOLE.NS_WS.Ajoute_UserResponse> Ajoute_UserAsync(CLIENT_CONSOLE.NS_WS.Ajoute_UserRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément Donne_UserResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Donne_User", ReplyAction="*")]
        CLIENT_CONSOLE.NS_WS.Donne_UserResponse Donne_User(CLIENT_CONSOLE.NS_WS.Donne_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Donne_User", ReplyAction="*")]
        System.Threading.Tasks.Task<CLIENT_CONSOLE.NS_WS.Donne_UserResponse> Donne_UserAsync(CLIENT_CONSOLE.NS_WS.Donne_UserRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément Donne_ListeResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Donne_Liste", ReplyAction="*")]
        CLIENT_CONSOLE.NS_WS.Donne_ListeResponse Donne_Liste(CLIENT_CONSOLE.NS_WS.Donne_ListeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Donne_Liste", ReplyAction="*")]
        System.Threading.Tasks.Task<CLIENT_CONSOLE.NS_WS.Donne_ListeResponse> Donne_ListeAsync(CLIENT_CONSOLE.NS_WS.Donne_ListeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Effacer_Liste", ReplyAction="*")]
        void Effacer_Liste();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Effacer_Liste", ReplyAction="*")]
        System.Threading.Tasks.Task Effacer_ListeAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ajoute_UserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ajoute_User", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT_CONSOLE.NS_WS.Ajoute_UserRequestBody Body;
        
        public Ajoute_UserRequest() {
        }
        
        public Ajoute_UserRequest(CLIENT_CONSOLE.NS_WS.Ajoute_UserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ajoute_UserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CLIENT_CONSOLE.NS_WS.C_USER P_User;
        
        public Ajoute_UserRequestBody() {
        }
        
        public Ajoute_UserRequestBody(CLIENT_CONSOLE.NS_WS.C_USER P_User) {
            this.P_User = P_User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ajoute_UserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ajoute_UserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT_CONSOLE.NS_WS.Ajoute_UserResponseBody Body;
        
        public Ajoute_UserResponse() {
        }
        
        public Ajoute_UserResponse(CLIENT_CONSOLE.NS_WS.Ajoute_UserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ajoute_UserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Ajoute_UserResult;
        
        public Ajoute_UserResponseBody() {
        }
        
        public Ajoute_UserResponseBody(int Ajoute_UserResult) {
            this.Ajoute_UserResult = Ajoute_UserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Donne_UserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Donne_User", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT_CONSOLE.NS_WS.Donne_UserRequestBody Body;
        
        public Donne_UserRequest() {
        }
        
        public Donne_UserRequest(CLIENT_CONSOLE.NS_WS.Donne_UserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Donne_UserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int P_Cle;
        
        public Donne_UserRequestBody() {
        }
        
        public Donne_UserRequestBody(int P_Cle) {
            this.P_Cle = P_Cle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Donne_UserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Donne_UserResponse", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT_CONSOLE.NS_WS.Donne_UserResponseBody Body;
        
        public Donne_UserResponse() {
        }
        
        public Donne_UserResponse(CLIENT_CONSOLE.NS_WS.Donne_UserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Donne_UserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CLIENT_CONSOLE.NS_WS.C_USER Donne_UserResult;
        
        public Donne_UserResponseBody() {
        }
        
        public Donne_UserResponseBody(CLIENT_CONSOLE.NS_WS.C_USER Donne_UserResult) {
            this.Donne_UserResult = Donne_UserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Donne_ListeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Donne_Liste", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT_CONSOLE.NS_WS.Donne_ListeRequestBody Body;
        
        public Donne_ListeRequest() {
        }
        
        public Donne_ListeRequest(CLIENT_CONSOLE.NS_WS.Donne_ListeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Donne_ListeRequestBody {
        
        public Donne_ListeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Donne_ListeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Donne_ListeResponse", Namespace="http://tempuri.org/", Order=0)]
        public CLIENT_CONSOLE.NS_WS.Donne_ListeResponseBody Body;
        
        public Donne_ListeResponse() {
        }
        
        public Donne_ListeResponse(CLIENT_CONSOLE.NS_WS.Donne_ListeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Donne_ListeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CLIENT_CONSOLE.NS_WS.C_USER[] Donne_ListeResult;
        
        public Donne_ListeResponseBody() {
        }
        
        public Donne_ListeResponseBody(CLIENT_CONSOLE.NS_WS.C_USER[] Donne_ListeResult) {
            this.Donne_ListeResult = Donne_ListeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface C_GESTION_USERSSoapChannel : CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class C_GESTION_USERSSoapClient : System.ServiceModel.ClientBase<CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap>, CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap {
        
        public C_GESTION_USERSSoapClient() {
        }
        
        public C_GESTION_USERSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public C_GESTION_USERSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public C_GESTION_USERSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public C_GESTION_USERSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CLIENT_CONSOLE.NS_WS.Ajoute_UserResponse CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap.Ajoute_User(CLIENT_CONSOLE.NS_WS.Ajoute_UserRequest request) {
            return base.Channel.Ajoute_User(request);
        }
        
        public int Ajoute_User(CLIENT_CONSOLE.NS_WS.C_USER P_User) {
            CLIENT_CONSOLE.NS_WS.Ajoute_UserRequest inValue = new CLIENT_CONSOLE.NS_WS.Ajoute_UserRequest();
            inValue.Body = new CLIENT_CONSOLE.NS_WS.Ajoute_UserRequestBody();
            inValue.Body.P_User = P_User;
            CLIENT_CONSOLE.NS_WS.Ajoute_UserResponse retVal = ((CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap)(this)).Ajoute_User(inValue);
            return retVal.Body.Ajoute_UserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CLIENT_CONSOLE.NS_WS.Ajoute_UserResponse> CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap.Ajoute_UserAsync(CLIENT_CONSOLE.NS_WS.Ajoute_UserRequest request) {
            return base.Channel.Ajoute_UserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CLIENT_CONSOLE.NS_WS.Ajoute_UserResponse> Ajoute_UserAsync(CLIENT_CONSOLE.NS_WS.C_USER P_User) {
            CLIENT_CONSOLE.NS_WS.Ajoute_UserRequest inValue = new CLIENT_CONSOLE.NS_WS.Ajoute_UserRequest();
            inValue.Body = new CLIENT_CONSOLE.NS_WS.Ajoute_UserRequestBody();
            inValue.Body.P_User = P_User;
            return ((CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap)(this)).Ajoute_UserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CLIENT_CONSOLE.NS_WS.Donne_UserResponse CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap.Donne_User(CLIENT_CONSOLE.NS_WS.Donne_UserRequest request) {
            return base.Channel.Donne_User(request);
        }
        
        public CLIENT_CONSOLE.NS_WS.C_USER Donne_User(int P_Cle) {
            CLIENT_CONSOLE.NS_WS.Donne_UserRequest inValue = new CLIENT_CONSOLE.NS_WS.Donne_UserRequest();
            inValue.Body = new CLIENT_CONSOLE.NS_WS.Donne_UserRequestBody();
            inValue.Body.P_Cle = P_Cle;
            CLIENT_CONSOLE.NS_WS.Donne_UserResponse retVal = ((CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap)(this)).Donne_User(inValue);
            return retVal.Body.Donne_UserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CLIENT_CONSOLE.NS_WS.Donne_UserResponse> CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap.Donne_UserAsync(CLIENT_CONSOLE.NS_WS.Donne_UserRequest request) {
            return base.Channel.Donne_UserAsync(request);
        }
        
        public System.Threading.Tasks.Task<CLIENT_CONSOLE.NS_WS.Donne_UserResponse> Donne_UserAsync(int P_Cle) {
            CLIENT_CONSOLE.NS_WS.Donne_UserRequest inValue = new CLIENT_CONSOLE.NS_WS.Donne_UserRequest();
            inValue.Body = new CLIENT_CONSOLE.NS_WS.Donne_UserRequestBody();
            inValue.Body.P_Cle = P_Cle;
            return ((CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap)(this)).Donne_UserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CLIENT_CONSOLE.NS_WS.Donne_ListeResponse CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap.Donne_Liste(CLIENT_CONSOLE.NS_WS.Donne_ListeRequest request) {
            return base.Channel.Donne_Liste(request);
        }
        
        public CLIENT_CONSOLE.NS_WS.C_USER[] Donne_Liste() {
            CLIENT_CONSOLE.NS_WS.Donne_ListeRequest inValue = new CLIENT_CONSOLE.NS_WS.Donne_ListeRequest();
            inValue.Body = new CLIENT_CONSOLE.NS_WS.Donne_ListeRequestBody();
            CLIENT_CONSOLE.NS_WS.Donne_ListeResponse retVal = ((CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap)(this)).Donne_Liste(inValue);
            return retVal.Body.Donne_ListeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CLIENT_CONSOLE.NS_WS.Donne_ListeResponse> CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap.Donne_ListeAsync(CLIENT_CONSOLE.NS_WS.Donne_ListeRequest request) {
            return base.Channel.Donne_ListeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CLIENT_CONSOLE.NS_WS.Donne_ListeResponse> Donne_ListeAsync() {
            CLIENT_CONSOLE.NS_WS.Donne_ListeRequest inValue = new CLIENT_CONSOLE.NS_WS.Donne_ListeRequest();
            inValue.Body = new CLIENT_CONSOLE.NS_WS.Donne_ListeRequestBody();
            return ((CLIENT_CONSOLE.NS_WS.C_GESTION_USERSSoap)(this)).Donne_ListeAsync(inValue);
        }
        
        public void Effacer_Liste() {
            base.Channel.Effacer_Liste();
        }
        
        public System.Threading.Tasks.Task Effacer_ListeAsync() {
            return base.Channel.Effacer_ListeAsync();
        }
    }
}
